# Generated by Django 5.2.4 on 2025-07-24 17:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aktualitatedetailpage_aktualitatespage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkspozicijasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Ievads')),
                ('body', wagtail.fields.StreamField([('virsraksts', 0), ('teksts', 1), ('attels', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Virsraksts'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Teksts'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Attēls'})}, verbose_name='Saturs')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
