# Generated by Django 5.2.4 on 2025-07-25 18:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_galerijaspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktualitatespage',
            name='intro',
        ),
        migrations.AddField(
            model_name='aktualitatespage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, default='Default content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=wagtail.fields.StreamField([('banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
