# Generated by Django 5.2.4 on 2025-07-27 13:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_aktualitatespage_intro_aktualitatespage_body_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('body', wagtail.fields.StreamField([('title', 0), ('text', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'})}, verbose_name='Содержимое')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='GalerijasPage',
            new_name='GalleryPage',
        ),
        migrations.RemoveField(
            model_name='aktualitatespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='ekspozicijaspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='AktualitateDetailPage',
        ),
        migrations.DeleteModel(
            name='AktualitatesPage',
        ),
        migrations.DeleteModel(
            name='EkspozicijasPage',
        ),
    ]
