# Generated by Django 5.2.4 on 2025-07-30 17:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventspage_kontaktipage_parmuzejupage_visitpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktualitatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Publicēšanas datums')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AktualitatesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EkspozicijasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Ievads')),
                ('body', wagtail.fields.StreamField([('title', 0), ('text', 1), ('image', 2), ('gallery', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Virsraksts'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Teksts'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Attēls'}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Attēlu saraksts', 'label': 'Galerija'})}, verbose_name='Saturs')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalerijasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('gallery', wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IzstadePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_from', models.DateField(verbose_name='Sākuma datums')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Beigu datums')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vieta')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('gallery', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Attēls'}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Galerija'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IzstadesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Ievads')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KrajumsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KrajumsItemPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('inventory_no', models.CharField(blank=True, max_length=100, verbose_name='Inventāra numurs')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Periods')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Apraksts')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, verbose_name='Attēli')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PakalpojumiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('services', wagtail.fields.StreamField([('service', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nosaukums'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Cena', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Apraksts', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 1), ('desc', 2)]], {})}, verbose_name='Pakalpojumi')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PetniecibaArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Autori')),
                ('date', models.DateField(verbose_name='Datums')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PetniecibaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SaitesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nosaukums'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Saite'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Apraksts', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'label': 'Atvērt jaunā cilnē', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('desc', 2), ('newtab', 3)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='visitpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ievads'),
        ),
        migrations.AlterField(
            model_name='kontaktipage',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adrese'),
        ),
        migrations.AlterField(
            model_name='kontaktipage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-pasts'),
        ),
        migrations.AlterField(
            model_name='kontaktipage',
            name='map_embed',
            field=models.TextField(blank=True, verbose_name='Kartes ieliktnis (iframe)'),
        ),
        migrations.AlterField(
            model_name='kontaktipage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tālrunis'),
        ),
        migrations.AlterField(
            model_name='parmuzejupage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.DeleteModel(
            name='EventDetailPage',
        ),
        migrations.DeleteModel(
            name='EventsPage',
        ),
        migrations.DeleteModel(
            name='VisitPage',
        ),
    ]
